### ISSUE TITLE
包长度异常

### ISSUE THREAD

**Issue by a08381** [bilive/bilive_server#18]
```
Jul 07 2020 10:23:46 : {
  status: 1,
  error: TypeError: 包长度异常
      at DMclientRE._ClientDataHandler (/www/wwwroot/bilive_server/build/bilive/lib/dm_client.js:185:71)
      at Socket.<anonymous> (/www/wwwroot/bilive_server/build/bilive/lib/dm_client.js:106:42)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23),
  data: <Buffer 48 54 54 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78 74 2f 68 74 6d 6c 0d 0a 43 6f 6e 74 65 6e 74 2d ... 220 more bytes>
}
```

**Comment by lzghzr** [comment]
正常，监听多了自然会出错，网卡路由或是内存都有可能出错
