### ISSUE TITLE
心跳超时

### ISSUE THREAD

**Issue by Me7426** [bilive/bilive_server#9]
```javascript
Jul 09 2019 14:44:30 : 尝试重连弹幕服务器失败，五分钟后再次重新连接

Jul 09 2019 14:42:32 : {
  status: 2,
  error: Error: 心跳超时
      at Timeout._onTimeout (/root/downloads/bilive_server/build/bilive/lib/dm_client.js:143:71)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

不清楚是不是之前大乱斗的活动过期的原因，但是其他弹幕都有正常监听

**Comment by lzghzr** [comment]
经常会有，不用担心
________________________________
